### ISSUE TITLE
Work more with objects, rather than with magic values

### ISSUE THREAD

**Issue by flavius** [Pabloss/flavius-aspra-mentoring-TicTacToe#11]
https://github.com/Pabloss/flavius-aspra-mentoring-TicTacToe/blob/536ae4ce1046b727d56ae0f2d9778b00be514baa/src/Game.php#L184

Here you're saving the symbol of a player, rather than the player.

In this particular application it's not that much of a big deal, but in complex application domains you want to work with whole objects, rather than some "details" like "the symbol X".

Refactor this array to hold instances of Player, rather than single characters. Use `null` for now for "no player".

**Comment by Pabloss** [comment]
Yes, you are totally right.
Saving objects allows us to save/record more information. 
Saving only e.g. one of their property we loose, make more narrower, the info of what we've done.
