### ISSUE TITLE
Validate Tile and Player during construction

### ISSUE THREAD

**Issue by flavius** [Pabloss/flavius-aspra-mentoring-TicTacToe#12]
In constructors which receive parameters, you should validate those parameters in all the possible ways.

If there is something wrong, throw an exception.

Throwing an exception in this case is fine, because it's the only way to prevent object construction.

You don't want to have objects which finish their initialization (the construtor exits without errors), but in terms of business rules, they are not in a valid state.

For instance, a Tile with a row or a column greater than 3.

Use very clear error codes different than 0 for the exceptions, and appropiate exceptions from the SPL: http://php.net/manual/en/spl.exceptions.php

**Comment by Pabloss** [comment]
fixed by 7263aacaf4a3c29188e98c594b06114132f309b1 commit
I forgot to add 'fixes #12' in message. But I did not want to do heavy edition on just have pushed commits.

**Comment by flavius** [comment]
@Pabloss good decision!
