### ISSUE TITLE
Game::players() allows creating more than two players, if they have different symbols

### ISSUE THREAD

**Issue by flavius** [Pabloss/flavius-aspra-mentoring-TicTacToe#13]
This is possible:

```
$game->players('1','2');
$game->players('3','4');
```

Why?

**Comment by Pabloss** [comment]
I'm not sure. I ran the test \TicTacToeTest\integration\GameTest and it did not allow to put code given above (I inserted it to the first test method).

**Comment by flavius** [comment]
Oh, I haven't tested it, I just "ran" the code in my mind. Since it was hard to "run in mind", maybe it's worth thinking how to structure and format the code such that it's easy to read, understand, and "run".

I've written the following test and I get an error:

![](https://i.imgur.com/ght9704.png)

![](https://i.imgur.com/S6IoaNr.png)

So it's not the error I thought you'd have, but there's an error.
