### ISSUE TITLE
Error handling is not clean

### ISSUE THREAD

**Issue by flavius** [Pabloss/flavius-aspra-mentoring-TicTacToe#2]
This is not a clean handling of errors:

https://github.com/Pabloss/flavius-aspra-mentoring-TicTacToe/blob/584a3d42937fc90dccb2af3a2a63645d77629e4d/src/TicTacToe/Game.php#L24

https://github.com/Pabloss/flavius-aspra-mentoring-TicTacToe/blob/584a3d42937fc90dccb2af3a2a63645d77629e4d/src/TicTacToe/Game.php#L58-L61

Because what would it involve showing the error message to the user in a html document, using output buffering?

That's why this solution solves your original problem, but it creates another one.

Instead, handle your error cases cleanly.

**Comment by Pabloss** [comment]
On the [page](https://www.toptal.com/abap/clean-code-and-the-art-of-exception-handling)  I found that Exceptions could be used but it is better to map structure of an application in structure of exceptions hierarchy too.

**Comment by flavius** [comment]
Bad input is daily routine in the lifetime of a program, so it's not exceptional. Users enter bad data all the time and they must get error messages.
Throwing an exception creates "random" execution paths, much like goto, and goto is bad.

It is really nothing exceptional about an user who enters invalid input.

PS: there is an argument which can convince me that exceptions are right in this case, but I will accept exceptions here only if you come with that argument, otherwise not.

**Comment by Pabloss** [comment]
Maybe you suggest not to use **Exception** suffix only (but Exceptions per se stil should be used).

**Comment by flavius** [comment]
I really mean what I said: nothing exceptional about bad user input, so no exceptions in this case. The name of the class is irrelevant.

**Comment by Pabloss** [comment]
So, I think next simple solution, would be just **to differ the errors by not to returning false on every error-like situation**, but **return the code - integer value that could be mapped to particular error case, and of course mapped to proper error message**.
