### ISSUE TITLE
Duplicate code not properly retrofitted allows the caller to create a mess

### ISSUE THREAD

**Issue by flavius** [Pabloss/flavius-aspra-mentoring-TicTacToe#3]
Here:

https://github.com/Pabloss/flavius-aspra-mentoring-TicTacToe/blob/584a3d42937fc90dccb2af3a2a63645d77629e4d/src/TicTacToe/Game.php#L11-L31

You wanted to retrofit the method `player()`, but instead you've left it intact and introduced a new method `players()` which does the right thing.

Now, the user of your `Game` class can still call `player()` and create a mess.

**Comment by Pabloss** [comment]
A new version doesn't include such duplication.
