### ISSUE TITLE
A tile should not be able to host another player, once it's already hosting a player

### ISSUE THREAD

**Issue by flavius** [Pabloss/flavius-aspra-mentoring-TicTacToe#4]
https://github.com/Pabloss/flavius-aspra-mentoring-TicTacToe/blob/584a3d42937fc90dccb2af3a2a63645d77629e4d/src/TicTacToe/Tile.php#L17

**Comment by Pabloss** [comment]
This will be removed at next commits.

**Comment by flavius** [comment]
Writing here 

> This will be removed at next commits.
And then closing this issue without the actual code has several drawbacks:

- alerts me of something happening, without something happening: I can't review the code, I just get the notification that I still have to wait and hope to see the change soon
- wastes your time and energy to comment and close it
- your comments don't add any value


Instead, do the following: when fixing an issue, write your usual commit message, but append to it "closes #4"

Example: "fix typo. Closes #4"

Then GitHub will close the issue when you push it, I get notified, and I have something to review.

Documentation: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by Pabloss** [comment]
Ok. Thx.
