### ISSUE TITLE
tests/src/GameTest contains non-unit-tests

### ISSUE THREAD

**Issue by flavius** [Pabloss/flavius-aspra-mentoring-TicTacToe#5]
These tests

https://github.com/Pabloss/flavius-aspra-mentoring-TicTacToe/blob/be6d01b53a3bb4cbc0aa9e9435db762463519592/tests/src/TicTacToe/GameTest.php#L12-L36

are not unit tests, because they don't test only one unit (e.g. they don't test only one method of a class).

If you'd turn code coverate on for these two tests, you'd see they cover other classes/methods than the ones in `TicTacToe\Game`.

**Comment by Pabloss** [comment]
I would like to say that I used code coverage options for very first time. I only have seen such analysis previously.  I have no big experience in this concept.

**Comment by Pabloss** [comment]
Do you say that **assertions check not Game but Player class**? I that good interpretation?

**Comment by flavius** [comment]
Yes, that's another way of putting it.

In 76b7607, you've fixed it by making the test an integration test. It's a great solution!
