### ISSUE TITLE
 starting a game should allow to repeat X player turn again 

### ISSUE THREAD

**Issue by flavius** [Pabloss/flavius-aspra-mentoring-TicTacToe#6]
I don't understand exactly which problem from the business domain you're solving with commits 5981600c4ff7bbd953728687152337f15d7a3439 and c7b32d420b2497fd01734bddb01398966077f2f7

For what is `Game::start()` and do you have a requirement / use case / scenario for that?

**Comment by Pabloss** [comment]
Yes, I'm also not sure if I overengineered it. I found that I could start again the game with other turns: just to include in test the case **when Player0 wins**. 
Of course, I would put that case in another test. I simply find more usages for it. E.g : _let's start the game again_. Just clean/reset the state.
